name: moodswing_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  go_router: ^12.0.1
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  dio: ^5.4.0
  flutter_secure_storage: ^5.0.2
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.8.0
  firebase_core:
  

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  retrofit_generator: '>=7.0.0 <8.0.0'
  
  json_serializable: ^6.6.0
  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/Icons/
    - asset/logo/