// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_KLrv0nJ1vz_ZYqY9zkGPVcYxHzC8Oc',
    appId: '1:1026527605300:web:b2d1103cc420f8a1889061',
    messagingSenderId: '1026527605300',
    projectId: 'moodswing-287cf',
    authDomain: 'moodswing-287cf.firebaseapp.com',
    storageBucket: 'moodswing-287cf.appspot.com',
    measurementId: 'G-1SDXD8BPCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-5k1DSmirgBqmXDBoeY6IF7QtJhl1-hc',
    appId: '1:1026527605300:android:a65c0f8362bf57ad889061',
    messagingSenderId: '1026527605300',
    projectId: 'moodswing-287cf',
    storageBucket: 'moodswing-287cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqSr8vP6IVMPkFAwIB6rk80d-VdTn-ro',
    appId: '1:1026527605300:ios:952308e332a4acc5889061',
    messagingSenderId: '1026527605300',
    projectId: 'moodswing-287cf',
    storageBucket: 'moodswing-287cf.appspot.com',
    iosBundleId: 'com.example.moodswingClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTqSr8vP6IVMPkFAwIB6rk80d-VdTn-ro',
    appId: '1:1026527605300:ios:7a03155c49dfec65889061',
    messagingSenderId: '1026527605300',
    projectId: 'moodswing-287cf',
    storageBucket: 'moodswing-287cf.appspot.com',
    iosBundleId: 'com.example.moodswingClient.RunnerTests',
  );
}
